export const constants = {
    GIST_REQUEST: 'GIST_REQUEST',
    GIST_SUCCESS: 'GIST_SUCCESS',
    GIST_FAILURE: 'GIST_FAILURE',
    FORK_REQUEST: 'FORK_REQUEST',
    FORK_SUCCESS: 'FORK_SUCCESS',
    FORK_FAILURE: 'FORK_FAILURE'
};
